frequency: 30
sensor_timeout: 0.3
two_d_mode: true

print_diagnostics: false

publish_tf: true

map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom


odom0: odom_wheel
odom0_config: [ true,  true, false,
                false, false, true,
                true, false, false,
                false, false, true,
                false, false, false]
odom0_queue_size: 2
odom0_differential: false
odom0_relative: true

odom1: odom_rf2o
odom1_config: [false,false,false,
                false,false,false,
                true,true,false,
                false, false, false,
                false, false, false]
odom1_queue_size: 5
odom1_differential: false
odom1_relative: true

imu0: imu
imu0_config: [false, false, false,
              false,  false,  true,
              false, false, false,
              false,  false,  true,
              false,  false,  false]
imu0_queue_size: 10
imu0_differential: false
imu0_relative: true

# [ADVANCED] Some IMUs automatically remove acceleration due to gravity, and others don't. If yours doesn't, please set
# this to true, and *make sure* your data conforms to REP-103, specifically, that the data is in ENU frame.
imu0_remove_gravitational_acceleration: true

use_control: true
control_config: [true, false, false, false, false, true]
