base_global_planner: "navfn/NavfnROS"
recovery_behavior_enabled: false
planner_frequency: 1.0
controller_frequency: 5.0


TrajectoryPlannerROS:
  acc_lim_x: 0.5
  acc_lim_y: 0
  acc_lim_theta: 0.5
  max_vel_x: 0.3
  min_vel_x: 0.12
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.35
  escape_vel: -0.15

  holonomic_robot: false

  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  sim_time: 2.75
  sim_granularity: 0.05
  angular_sim_granularity: 0.05
  vx_samples: 20
  vtheta_samples: 20


  pdist_scale: 0.9
  gdist_scale: 0.6
  occdist_scale: 0.05

