base_global_planner: "navfn/NavfnROS"
recovery_behavior_enabled: false
planner_frequency: 1.0
controller_frequency: 5.0


TrajectoryPlannerROS:
  acc_lim_x: 0.3
  acc_lim_y: 0
  acc_lim_theta: 0.1
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.25

  sim_time: 3.0
  pdist_scale: 0.8
  gdist_scale: 0.6


  


  holonomic_robot: false
