obstacle_range: 2.0
raytrace_range: 2.5


transform_tolerance: 0.5
footprint: [[-0.43,-0.25],[-0.43,0.25],[0.07,0.26],[0.20,0],[0.07,-0.26]]
# footprint: 0.01

map_type: cost_map


# observation_sources: scan bump
observation_sources: scan

scan: {
        data_type: LaserScan,
        sensor_frame: laser_frame,
        topic: /scan,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.0, 
        max_obstacle_height: 0.5
      }
# Can we just set up two of these here?
#bump: {
#        data_type: PointCloud2, 
#        topic: mobile_base/sensors/bumper_pointcloud, 
#        marking: true, 
#        clearing: false, 
#        min_obstacle_height: 0.0, 
#        max_obstacle_height: 0.15
#      }
