obstacle_range: 5.5
raytrace_range: 3.0
footprint: [[-0.15,-0.25],[-0.15,0.25],[0.45,0.26],[0.53,0],[0.45,-0.26]]
footprint_padding: 0.15

observation_sources: laser_scan_sensor #point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
