# static_map - True if using existing map

global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 0.09
  static_map: true
  width: 10.0
  height: 10.0
  inflation_radius: 3.0
  cost_scaling_factor: 3.0
  inflate_unknown: true
  