local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 7
   height: 7
   resolution: 0.08
   inflation_radius: 0.5
   cost_scaling_factor: 5.0
